### ISSUE TITLE
求一份clash安装包

### ISSUE THREAD

**Issue by zengchen233** [afeng616/Build-Cozy-Ubuntu-Environment#1]
repo主你好，求一份clash安装包😢

**Comment by afeng616** [comment]
抱歉之前一直没有找到相应的能用的软件，这次经过测试发现了新的程序，希望还能帮到你。

https://www.speeder.one/client-download/Clash.for.Windows-x64-linux.tar.gz

下载后解压，所需的文件就俩，clash运行文件在resources/static/files/linux/x64/，Country.mmdb在resources/static/files/default下，其他操作一切照旧。
